### ISSUE TITLE
HTTP 401 is missing

### ISSUE THREAD

**Issue by settermjd** [teapot-php/status-code#18]
Hi folks, in https://github.com/teapot-php/status-code/blob/master/src/RFC/RFC7231.php, any reason why HTTP 401 is missing?

**Comment by localheinz** [comment]
@settermjd 

It is defined in

https://github.com/teapot-php/status-code/blob/v1.1.2/src/RFC/RFC2616.php#L448

and

https://github.com/teapot-php/status-code/blob/v1.1.2/src/RFC/RFC7235.php#L71

The constant is also accessible via `Teapot\StatusCode\Http::UNAUTHORIZED`.

```php
<?php

use Teapot\StatusCode;

require_once __DIR__ . '/vendor/autoload.php';

var_dump(StatusCode\Http::UNAUTHORIZED); // int(401)
```

Do you think it should be defined in a different interface?

**Comment by localheinz** [comment]
Thank you, @settermjd!
